language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"
  
os: linux
arch:
  - amd64
  - arm64
  
install:
  - pip install coverage
  - pip install pypack

script:
  # run tests with coverage
  - coverage run tests/run_tests.py
  - coverage report -m
  # test distribution packaging
  - python -m pypack patch.py
